### ISSUE TITLE
总是训练失败是怎么回事？

### ISSUE THREAD

**Issue by jiaenqiu** [yeyupiaoling/PunctuationModel#11]
# 单机单卡
python train.py
中断退出信息如下：
<img width="1454" alt="image" src="https://github.com/yeyupiaoling/PunctuationModel/assets/26378685/5b72f1e6-07d1-46a8-be6e-418a75467700">

<img width="1160" alt="image" src="https://github.com/yeyupiaoling/PunctuationModel/assets/26378685/5126a0d1-22cb-4b67-b3a4-d5e779d0d78c">

# 单价多卡
python -m paddle.distributed.launch --devices=0,1 train.py
中断退出信息如下：
<img width="1442" alt="image" src="https://github.com/yeyupiaoling/PunctuationModel/assets/26378685/0e85c141-3ae3-4d36-badc-f31e23eb9871">

<img width="837" alt="image" src="https://github.com/yeyupiaoling/PunctuationModel/assets/26378685/52db279f-673b-46b6-941c-4adeaea4e3ce">

**Comment by yeyupiaoling** [comment]
直接这样中断，我也看不出是什么问题，显存是否足够？
