### ISSUE TITLE
解码器

### ISSUE THREAD

**Issue by happywch** [yeyupiaoling/PunctuationModel#14]
为什么集束搜索解码器需要在linux'上才能使用，有没有什么方法能够让他支持在windows上

**Comment by yeyupiaoling** [comment]
这不是语音识别上面的吗？masr和PPASR都支持Windows的

**Comment by happywch** [comment]
不好意思，确实发错地方了。我想问的是MASR的提供的在ctc集束搜索解码器，文档中说他只能在linux上使用，有什么方法能在windows上使用吗

**Comment by yeyupiaoling** [comment]
你看了很旧的文档了吧！
