### ISSUE TITLE
如何保持英文單詞之間的空格？

### ISSUE THREAD

**Issue by shaynemei** [yeyupiaoling/PunctuationModel#15]
for example:

INPUT: 标点符号模型加载成功AND YOU STILL RE

CURRENT OUPUT: 标点符号模型加载成功，andyoustillre。

EXPECTED OUTPUT: 标点符号模型加载成功，and you still re。

**Comment by yeyupiaoling** [comment]
或许你可以针对每个英文ttoken来加一个空格。

**Comment by terryops** [comment]
> 或许你可以针对每个英文ttoken来加一个空格。

请问具体怎么做呢？中英混合的句子很多，出现这种没有空格的问题很麻烦。
