### ISSUE TITLE
大佬，有点不太明白这块标签有什么用？得到的labels全是0

### ISSUE THREAD

**Issue by yangy996** [yeyupiaoling/PunctuationModel#17]
if word in self.punc2id.keys()这一行会把标签数据全部过滤掉，punc2id中带有了空格数据

                label, input_data = [], []
                for i in range(len(txt) - 1):
                    # 获取输入数据
                    word = txt[i]
                    if word in self.punc2id.keys():
                        continue
                    token = self.tokenizer(word)
                    x = token["input_ids"][1:-1]
                    input_data.extend(x)
                    # 获取标签数据
                    punc = txt[i + 1]

**Comment by yeyupiaoling** [comment]
0就不加标点符号，其他的对应标点符号
