### ISSUE TITLE
这个输入的text有字长限制吗？

### ISSUE THREAD

**Issue by raycool** [yeyupiaoling/PunctuationModel#2]
输入输出text过长的话，貌似没有任何效果，不会添加任何标点符号。
这个对输入长度有限制吗？如果没有的话，我应该怎么来优化这个模型。
谢谢。

**Comment by yeyupiaoling** [comment]
这个得看训练文本，本项目是训练最长的事100个字符。

**Comment by raycool** [comment]
谢谢答复，刚看了下源码看到了训练长度。
再次感谢您的解答。
