### ISSUE TITLE
请把模型下载链接放到网盘上吧

### ISSUE THREAD

**Issue by uuleaf** [yeyupiaoling/PunctuationModel#3]
CSDN现在不正经啊，天天割韭菜。

![image](https://user-images.githubusercontent.com/6434727/200804352-06b169da-f150-43b1-99ff-0255f2e76c5c.png)
![image](https://user-images.githubusercontent.com/6434727/200804382-d2e7ba64-b1f9-4603-ac02-313a85951ce4.png)

**Comment by yeyupiaoling** [comment]
放在网盘麻烦
