### ISSUE TITLE
封装

### ISSUE THREAD

**Issue by xbsdsongnan** [yeyupiaoling/PunctuationModel#4]
在windows下可否像ocr那样封装一下呢？

**Comment by yeyupiaoling** [comment]
打包成windows，这个我不擅长。你自己试一下是否可以。

**Comment by xbsdsongnan** [comment]
每次都要在根目录读取基模型，这个怎么修改呢

**Comment by yeyupiaoling** [comment]
这里修改的
https://github.com/yeyupiaoling/PunctuationModel/blob/02667f85d8404da46c1e3ca2ef87c644eaba37a9/infer.py#L10

**Comment by xbsdsongnan** [comment]
在windows下C盘有个.paddlenlp文件夹，里面每次都读取，如果没有，就会联网下载，怎么处理

**Comment by yeyupiaoling** [comment]
你可以把`ernie-1.0`目录复制到项目根目录，然后修改为`./ernie-1.0`

https://github.com/yeyupiaoling/PunctuationModel/blob/02667f85d8404da46c1e3ca2ef87c644eaba37a9/utils/predictor.py#L24
