### ISSUE TITLE
试过小数点. 和百分号% ，处理正确吗？

### ISSUE THREAD

**Issue by anyshu** [yeyupiaoling/PunctuationModel#7]
使用paddlespeech处理，发现有错误

from paddlespeech.cli.text.infer import TextExecutor
text_punc = TextExecutor()
result = text_punc(text="今天的天气真不错啊你下午有空吗我想约你一起去吃饭一共3.9元占预算10%")
今天的天气真不错啊！你下午有空吗？我想约你一起去吃饭，一共39元，占预算：10。

**Comment by yeyupiaoling** [comment]
没有试过，只试过标点符号，我觉得也是可以的
