### ISSUE TITLE
python train.py后, 是否支持"断点续训"?

### ISSUE THREAD

**Issue by gadmyth** [yeyupiaoling/PunctuationModel#9]
下载iwslt2012数据集并解压到相应的目录下后, 执行python train.py一段时间后, 每训练1代, 都会将模型保存在models/checkpoint目录下, 一共要训练100代

如果训练到67代后, ctrl+c中断训练后, 再次执行python train.py后, 是否会断点续训, 直接从第67代开始继续训练?

**Comment by yeyupiaoling** [comment]
不能哦。因为我当初考虑的是只训练三轮，所以没必要搞这种。
